### ISSUE TITLE
Cannot find module 'fly-util'

### ISSUE THREAD

**Issue by elliottsj** [lukeed/taskr#134]
Using Node 5.1.0 via nvm:

``` shell
$ nvm use 5.1.0
Now using node v5.1.0 (npm v3.3.12)

$ npm i -g fly
/Users/spencerelliott/.nvm/versions/node/v5.1.0/bin/fly -> /Users/spencerelliott/.nvm/versions/node/v5.1.0/lib/node_modules/fly/bin/index

> fsevents@1.0.6 install /Users/spencerelliott/.nvm/versions/node/v5.1.0/lib/node_modules/fly/node_modules/fsevents
> node-pre-gyp install --fallback-to-build

[fsevents] Success: "/Users/spencerelliott/.nvm/versions/node/v5.1.0/lib/node_modules/fly/node_modules/fsevents/lib/binding/Release/node-v47-darwin-x64/fse.node" is installed via remote
/Users/spencerelliott/.nvm/versions/node/v5.1.0/lib
└─┬ fly@0.8.6 
  ├─┬ babel-runtime@5.8.35 
  │ └── core-js@1.2.6 
  ├─┬ chokidar@1.4.2 
  │ ├─┬ anymatch@1.3.0 
  │ │ ├── arrify@1.0.1 
  │ │ └─┬ micromatch@2.3.7 
  │ │   ├─┬ arr-diff@2.0.0 
  │ │   │ └── arr-flatten@1.0.1 
  │ │   ├── array-unique@0.2.1 
  │ │   ├─┬ braces@1.8.3 
  │ │   │ ├─┬ expand-range@1.8.1 
  │ │   │ │ └─┬ fill-range@2.2.3 
  │ │   │ │   ├── is-number@2.1.0 
  │ │   │ │   ├── isobject@2.0.0 
  │ │   │ │   ├── randomatic@1.1.5 
  │ │   │ │   └── repeat-string@1.5.2 
  │ │   │ ├── preserve@0.2.0 
  │ │   │ └── repeat-element@1.1.2 
  │ │   ├── expand-brackets@0.1.4 
  │ │   ├── extglob@0.3.2 
  │ │   ├── filename-regex@2.0.0 
  │ │   ├─┬ kind-of@3.0.2 
  │ │   │ └── is-buffer@1.1.1 
  │ │   ├── normalize-path@2.0.1 
  │ │   ├─┬ object.omit@2.0.0 
  │ │   │ ├─┬ for-own@0.1.3 
  │ │   │ │ └── for-in@0.1.4 
  │ │   │ └── is-extendable@0.1.1 
  │ │   ├─┬ parse-glob@3.0.4 
  │ │   │ ├── glob-base@0.3.0 
  │ │   │ └── is-dotfile@1.0.2 
  │ │   └─┬ regex-cache@0.4.2 
  │ │     ├── is-equal-shallow@0.1.3 
  │ │     └── is-primitive@2.0.0 
  │ ├── async-each@0.1.6 
  │ ├─┬ fsevents@1.0.6 
  │ │ ├── nan@2.2.0 
  │ │ └─┬ node-pre-gyp@0.6.17
  │ │   ├─┬ mkdirp@0.5.1 
  │ │   │ └── minimist@0.0.8 
  │ │   ├─┬ npmlog@2.0.0
  │ │   │ └─┬ are-we-there-yet@1.0.4
  │ │   │   └─┬ readable-stream@1.1.13
  │ │   │     ├── core-util-is@1.0.2 
  │ │   │     ├── isarray@0.0.1 
  │ │   │     └── string_decoder@0.10.31 
  │ │   ├─┬ rc@1.1.5
  │ │   │ ├── ini@1.3.4 
  │ │   │ ├── minimist@1.2.0 
  │ │   │ └── strip-json-comments@1.0.4 
  │ │   ├─┬ request@2.67.0
  │ │   │ ├─┬ bl@1.0.0
  │ │   │ │ └─┬ readable-stream@2.0.4
  │ │   │ │   ├── core-util-is@1.0.2 
  │ │   │ │   ├── inherits@2.0.1 
  │ │   │ │   ├── isarray@0.0.1 
  │ │   │ │   ├── string_decoder@0.10.31 
  │ │   │ │   └── util-deprecate@1.0.2 
  │ │   │ └─┬ har-validator@2.0.3
  │ │   │   ├─┬ chalk@1.1.1 
  │ │   │   │ ├── ansi-styles@2.1.0 
  │ │   │   │ ├─┬ has-ansi@2.0.0 
  │ │   │   │ │ └── ansi-regex@2.0.0 
  │ │   │   │ ├── strip-ansi@3.0.0 
  │ │   │   │ └── supports-color@2.0.0 
  │ │   │   ├─┬ commander@2.9.0 
  │ │   │   │ └── graceful-readlink@1.0.1 
  │ │   │   ├─┬ is-my-json-valid@2.12.3
  │ │   │   │ └── xtend@4.0.1 
  │ │   │   └─┬ pinkie-promise@2.0.0 
  │ │   │     └── pinkie@2.0.1 
  │ │   ├─┬ rimraf@2.4.4
  │ │   │ └─┬ glob@5.0.15 
  │ │   │   ├─┬ inflight@1.0.4 
  │ │   │   │ └── wrappy@1.0.1 
  │ │   │   ├── inherits@2.0.1 
  │ │   │   ├─┬ minimatch@3.0.0
  │ │   │   │ └─┬ brace-expansion@1.1.1
  │ │   │   │   └── concat-map@0.0.1 
  │ │   │   ├─┬ once@1.3.3 
  │ │   │   │ └── wrappy@1.0.1 
  │ │   │   └── path-is-absolute@1.0.0 
  │ │   ├── semver@5.1.0 
  │ │   ├─┬ tar@2.2.1
  │ │   │ └── inherits@2.0.1 
  │ │   └─┬ tar-pack@3.1.0
  │ │     ├─┬ fstream-ignore@1.0.3
  │ │     │ └─┬ minimatch@3.0.0
  │ │     │   └─┬ brace-expansion@1.1.1
  │ │     │     └── concat-map@0.0.1 
  │ │     ├── graceful-fs@4.1.2 
  │ │     └─┬ readable-stream@1.0.33
  │ │       ├── core-util-is@1.0.2 
  │ │       ├── inherits@2.0.1 
  │ │       ├── isarray@0.0.1 
  │ │       └── string_decoder@0.10.31 
  │ ├── glob-parent@2.0.0 
  │ ├── inherits@2.0.1 
  │ ├─┬ is-binary-path@1.0.1 
  │ │ └── binary-extensions@1.4.0 
  │ ├─┬ is-glob@2.0.1 
  │ │ └── is-extglob@1.0.0 
  │ ├── path-is-absolute@1.0.0 
  │ └─┬ readdirp@2.0.0 
  │   ├── graceful-fs@4.1.2 
  │   ├─┬ minimatch@2.0.10 
  │   │ └─┬ brace-expansion@1.1.2 
  │   │   ├── balanced-match@0.3.0 
  │   │   └── concat-map@0.0.1 
  │   └─┬ readable-stream@2.0.5 
  │     ├── core-util-is@1.0.2 
  │     ├── isarray@0.0.1 
  │     ├── process-nextick-args@1.0.6 
  │     ├── string_decoder@0.10.31 
  │     └── util-deprecate@1.0.2 
  ├─┬ clor@2.0.2 
  │ └── ansi-styles@2.1.0 
  ├── co@4.6.0 
  ├── concat-with-sourcemaps@1.0.4 
  ├─┬ debug@2.2.0 
  │ └── ms@0.7.1 
  ├─┬ fly-util@4.4.0 
  │ ├─┬ babel-core@5.8.35 
  │ │ ├── babel-plugin-constant-folding@1.0.1 
  │ │ ├── babel-plugin-dead-code-elimination@1.0.2 
  │ │ ├── babel-plugin-eval@1.0.1 
  │ │ ├── babel-plugin-inline-environment-variables@1.0.1 
  │ │ ├── babel-plugin-jscript@1.0.4 
  │ │ ├── babel-plugin-member-expression-literals@1.0.1 
  │ │ ├── babel-plugin-property-literals@1.0.1 
  │ │ ├── babel-plugin-proto-to-assign@1.0.4 
  │ │ ├── babel-plugin-react-constant-elements@1.0.3 
  │ │ ├── babel-plugin-react-display-name@1.0.3 
  │ │ ├── babel-plugin-remove-console@1.0.1 
  │ │ ├── babel-plugin-remove-debugger@1.0.1 
  │ │ ├── babel-plugin-runtime@1.0.7 
  │ │ ├─┬ babel-plugin-undeclared-variables-check@1.0.2 
  │ │ │ └── leven@1.0.2 
  │ │ ├── babel-plugin-undefined-to-void@1.1.6 
  │ │ ├── babylon@5.8.35 
  │ │ ├── bluebird@2.10.2 
  │ │ ├── convert-source-map@1.1.3 
  │ │ ├── detect-indent@3.0.1 
  │ │ ├── esutils@2.0.2 
  │ │ ├── fs-readdir-recursive@0.1.2 
  │ │ ├── globals@6.4.1 
  │ │ ├─┬ home-or-tmp@1.0.0 
  │ │ │ └── user-home@1.1.1 
  │ │ ├── is-integer@1.0.6 
  │ │ ├── js-tokens@1.0.1 
  │ │ ├── json5@0.4.0 
  │ │ ├─┬ line-numbers@0.2.0 
  │ │ │ └── left-pad@0.0.3 
  │ │ ├── lodash@3.10.1 
  │ │ ├─┬ output-file-sync@1.1.1 
  │ │ │ └── xtend@4.0.1 
  │ │ ├── path-exists@1.0.0 
  │ │ ├── private@0.1.6 
  │ │ ├─┬ regenerator@0.8.40 
  │ │ │ ├─┬ commoner@0.10.4 
  │ │ │ │ ├─┬ commander@2.9.0 
  │ │ │ │ │ └── graceful-readlink@1.0.1 
  │ │ │ │ ├─┬ detective@4.3.1 
  │ │ │ │ │ ├── acorn@1.2.2 
  │ │ │ │ │ └── defined@1.0.0 
  │ │ │ │ ├── glob@5.0.15 
  │ │ │ │ ├── iconv-lite@0.4.13 
  │ │ │ │ └── q@1.4.1 
  │ │ │ ├─┬ defs@1.1.1 
  │ │ │ │ ├─┬ alter@0.2.0 
  │ │ │ │ │ └── stable@0.1.5 
  │ │ │ │ ├── ast-traverse@0.1.1 
  │ │ │ │ ├── breakable@1.0.0 
  │ │ │ │ ├── simple-fmt@0.1.0 
  │ │ │ │ ├── simple-is@0.2.0 
  │ │ │ │ ├── stringmap@0.2.2 
  │ │ │ │ ├── stringset@0.2.1 
  │ │ │ │ ├── tryor@0.1.2 
  │ │ │ │ └─┬ yargs@3.27.0 
  │ │ │ │   ├── camelcase@1.2.1 
  │ │ │ │   ├─┬ cliui@2.1.0 
  │ │ │ │   │ ├─┬ center-align@0.1.2 
  │ │ │ │   │ │ ├─┬ align-text@0.1.3 
  │ │ │ │   │ │ │ ├── kind-of@2.0.1 
  │ │ │ │   │ │ │ └── longest@1.0.1 
  │ │ │ │   │ │ └── lazy-cache@0.2.7 
  │ │ │ │   │ ├── right-align@0.1.3 
  │ │ │ │   │ └── wordwrap@0.0.2 
  │ │ │ │   ├─┬ os-locale@1.4.0 
  │ │ │ │   │ └─┬ lcid@1.0.0 
  │ │ │ │   │   └── invert-kv@1.0.0 
  │ │ │ │   ├── window-size@0.1.4 
  │ │ │ │   └── y18n@3.2.0 
  │ │ │ ├── esprima-fb@15001.1001.0-dev-harmony-fb 
  │ │ │ ├─┬ recast@0.10.33 
  │ │ │ │ └── ast-types@0.8.12 
  │ │ │ └── through@2.3.8 
  │ │ ├─┬ regexpu@1.3.0 
  │ │ │ ├── esprima@2.7.1 
  │ │ │ ├── regenerate@1.2.1 
  │ │ │ ├── regjsgen@0.2.0 
  │ │ │ └─┬ regjsparser@0.1.5 
  │ │ │   └── jsesc@0.5.0 
  │ │ ├── resolve@1.1.7 
  │ │ ├── shebang-regex@1.0.0 
  │ │ ├── slash@1.0.0 
  │ │ ├─┬ source-map-support@0.2.10 
  │ │ │ └─┬ source-map@0.1.32 
  │ │ │   └── amdefine@1.0.0 
  │ │ ├── to-fast-properties@1.0.1 
  │ │ ├── trim-right@1.0.1 
  │ │ └── try-resolve@1.0.1 
  │ ├── clor@1.6.0 
  │ ├─┬ dateformat@1.0.12 
  │ │ ├── get-stdin@4.0.1 
  │ │ └─┬ meow@3.7.0 
  │ │   ├─┬ camelcase-keys@2.0.0 
  │ │   │ └── camelcase@2.1.0 
  │ │   ├── decamelize@1.1.2 
  │ │   ├─┬ loud-rejection@1.2.0 
  │ │   │ └── signal-exit@2.1.2 
  │ │   ├── map-obj@1.0.1 
  │ │   ├─┬ normalize-package-data@2.3.5 
  │ │   │ ├── hosted-git-info@2.1.4 
  │ │   │ ├─┬ is-builtin-module@1.0.0 
  │ │   │ │ └── builtin-modules@1.1.1 
  │ │   │ └─┬ validate-npm-package-license@3.0.1 
  │ │   │   ├─┬ spdx-correct@1.0.2 
  │ │   │   │ └── spdx-license-ids@1.2.0 
  │ │   │   └─┬ spdx-expression-parse@1.0.2 
  │ │   │     └── spdx-exceptions@1.0.4 
  │ │   ├─┬ read-pkg-up@1.0.1 
  │ │   │ ├─┬ find-up@1.1.0 
  │ │   │ │ └── path-exists@2.1.0 
  │ │   │ └─┬ read-pkg@1.1.0 
  │ │   │   ├─┬ load-json-file@1.1.0 
  │ │   │   │ ├─┬ parse-json@2.2.0 
  │ │   │   │ │ └─┬ error-ex@1.3.0 
  │ │   │   │ │   └── is-arrayish@0.2.1 
  │ │   │   │ └─┬ strip-bom@2.0.0 
  │ │   │   │   └── is-utf8@0.2.1 
  │ │   │   └── path-type@1.1.0 
  │ │   ├─┬ redent@1.0.0 
  │ │   │ ├─┬ indent-string@2.1.0 
  │ │   │ │ └── repeating@2.0.0 
  │ │   │ └── strip-indent@1.0.1 
  │ │   └── trim-newlines@1.0.0 
  │ ├─┬ globby@4.0.0 
  │ │ ├─┬ array-union@1.0.1 
  │ │ │ └── array-uniq@1.0.2 
  │ │ ├── glob@6.0.4 
  │ │ ├── pify@2.3.0 
  │ │ └─┬ pinkie-promise@2.0.0 
  │ │   └── pinkie@2.0.1 
  │ └── interpret@0.6.6 
  ├── interpret@1.0.0 
  ├─┬ mkdirp@0.5.1 
  │ └── minimist@0.0.8 
  ├─┬ mz@2.2.0 
  │ ├── native-or-bluebird@1.2.0 
  │ ├── object-assign@4.0.1 
  │ └─┬ thenify-all@1.6.0 
  │   └── thenify@3.1.1 
  ├── parsec@1.5.3 
  ├─┬ prettyjson@1.1.3 
  │ ├── colors@1.1.2 
  │ └── minimist@1.2.0 
  ├─┬ rimraf@2.5.1 
  │ └─┬ glob@6.0.4 
  │   ├─┬ inflight@1.0.4 
  │   │ └── wrappy@1.0.1 
  │   └── once@1.3.3 
  ├── source-map@0.5.3 
  └─┬ update-notifier@0.5.0 
    ├─┬ chalk@1.1.1 
    │ ├── escape-string-regexp@1.0.4 
    │ ├─┬ has-ansi@2.0.0 
    │ │ └── ansi-regex@2.0.0 
    │ ├── strip-ansi@3.0.0 
    │ └── supports-color@2.0.0 
    ├─┬ configstore@1.4.0 
    │ ├── os-tmpdir@1.0.1 
    │ ├─┬ osenv@0.1.3 
    │ │ └── os-homedir@1.0.1 
    │ ├── uuid@2.0.1 
    │ ├─┬ write-file-atomic@1.1.4 
    │ │ ├── imurmurhash@0.1.4 
    │ │ └── slide@1.1.6 
    │ └── xdg-basedir@2.0.0 
    ├── is-npm@1.0.0 
    ├─┬ latest-version@1.0.1 
    │ └─┬ package-json@1.2.0 
    │   ├─┬ got@3.3.1 
    │   │ ├─┬ duplexify@3.4.2 
    │   │ │ └── end-of-stream@1.0.0 
    │   │ ├── infinity-agent@2.0.3 
    │   │ ├── is-redirect@1.0.0 
    │   │ ├── is-stream@1.0.1 
    │   │ ├── lowercase-keys@1.0.0 
    │   │ ├── nested-error-stacks@1.0.2 
    │   │ ├── object-assign@3.0.0 
    │   │ ├── prepend-http@1.0.3 
    │   │ ├─┬ read-all-stream@3.0.1 
    │   │ │ └─┬ pinkie-promise@1.0.0 
    │   │ │   └── pinkie@1.0.0 
    │   │ └── timed-out@2.0.0 
    │   └─┬ registry-url@3.0.3 
    │     └─┬ rc@1.1.6 
    │       ├── deep-extend@0.4.1 
    │       ├── ini@1.3.4 
    │       └── strip-json-comments@1.0.4 
    ├─┬ repeating@1.1.3 
    │ └─┬ is-finite@1.0.1 
    │   └── number-is-nan@1.0.0 
    ├─┬ semver-diff@2.1.0 
    │ └── semver@5.1.0 
    └── string-length@1.0.1 

$ fly --help                                                                                                                            12:12:16
module.js:340
    throw err;
    ^

Error: Cannot find module 'fly-util'
    at Function.Module._resolveFilename (module.js:338:15)
    at Function.Module._load (module.js:289:25)
    at Module.require (module.js:366:17)
    at require (module.js:385:17)
    at Object.<anonymous> (/Users/spencerelliott/.nvm/versions/node/v5.1.0/lib/node_modules/fly/dist/fly.js:68:16)
    at Module._compile (module.js:425:26)
    at Object.Module._extensions..js (module.js:432:10)
    at Module.load (module.js:356:32)
    at Function.Module._load (module.js:313:12)
    at Module.require (module.js:366:17)
    at require (module.js:385:17)
    at Object.<anonymous> (/Users/spencerelliott/.nvm/versions/node/v5.1.0/lib/node_modules/fly/dist/cli/spawn.js:13:12)
    at Module._compile (module.js:425:26)
    at Object.Module._extensions..js (module.js:432:10)
    at Module.load (module.js:356:32)
    at Function.Module._load (module.js:313:12)
```

**Comment by lukeed** [comment]
Fixing it right now -- just ran into it too after updating fly-util

**Comment by lukeed** [comment]
@elliottsj Please try again. Let me know if you had the same success I did. :)

**Comment by elliottsj** [comment]
Great, works now using `fly@0.8.7`. Thanks!

``` shell
$ fly --help                                                                                                                            13:44:01

Usage
  fly [options] [tasks]

Options
  -h  --help     Display this help.
  -f  --file     Use an alternate Flyfile.
  -l  --list     Display available tasks.
  -v  --version  Display version.
```

**Comment by lukeed** [comment]
Great! Glad it worked out for you too
